### ISSUE TITLE
Support relative destination path for container copy files

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#552]
**Description:**

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Thevakumar-Luheerathan** [comment]
This improvement should contain following scopes.

- Both absolute path and relative path should be supported by `Cloud.toml copy` command. (Relative path is based on the directory where `Cloud.toml` resides in the case of source, while it is based on working directory in the case of destination within container.)

- Instead of copy file by file, A complete folder can be copied to the the container.

**Comment by Thevakumar-Luheerathan** [comment]
Existing implementation supports all these scopes
